repos:
  - repo: https://gitlab.com/vojko.pribudic/pre-commit-update
    rev: v0.1.1
    hooks:
      - id: pre-commit-update

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.5.7'
    hooks:
      - id: ruff
        args: [check, src, --select, I, --fix, --exit-non-zero-on-fix]