repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.3.2
    hooks:
      - id: pre-commit-update
        name: Auto-update pre-commit hooks

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: '24.8.0'
    hooks:
      - id: black
        name: Format with Black
        args: [src/]

      - id: black-jupyter
        name: Format jupyter with Black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.5.7'
    hooks:
      ## Imports
      - id: ruff
        name: Ruff imports check
        types_or: [ python, pyi, jupyter ]
        args: [--select, I, --fix, --exit-zero]
      
      ## Lint
      - id: ruff
        name: Ruff formatting check
        types_or: [ python, pyi, jupyter ]
        args: [--fix, --exit-zero]
